name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  CI:
    
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        uses: docker/login-action@v2
      - uses: actions/checkout@v3
        with:
          username: ${{  secrets.USER  }}
          password: ${{  secrets.PASSWD  }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        
        with:
        
          context:  .
          push: true
          tags: |
            luc4592/trabalho-ci:v1
            luc4592/trabalho-ci:latest
            
