name: Example workflow for Maven using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: RunSnyk to check for vulnerabilities
        uses: snyk/actions/maven@master
      - name: npm/yarn/pnpm install
  # You may pin to the exact commit or the version.
  # uses: Jaid/action-npm-install@9483da054882538350947c4147de4c8adbf0d597
        uses: Jaid/action-npm-install@v1.2.4
        #continue-on-error: true
        env:
          SNYK_TOKEN: ee3f5a48-f938-45cb-a3ef-63ee5143a564
